services:
  timescaledb:
    image: timescale/timescaledb:latest-pg18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./seed/cpu_usage.sql:/docker-entrypoint-initdb.d/cpu_usage.sql
      - ./seed/cpu_usage.csv:/seed/cpu_usage.csv
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  tsbench:
    build: .
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - ${TSBENCH_FILE:-./input/query_params.csv}:/data.csv
    command:
      - "--database"
      - "${TSBENCH_DATABASE:-postgres://postgres:password@timescaledb:5432/homework}"
      - "--file"
      - "/data.csv"
      - "--workers"
      - "${TSBENCH_WORKERS:-3}"
      - "--query-timeout"
      - "${TSBENCH_QUERY_TIMEOUT:-100ms}"
